name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v1
      - name: IFTTT Webhook
        uses: ./.
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        with:
          key: ${{ secrets.IFTTT_KEY }}
          event: cron_notify
          value1: github
          value2: iffttt Webhook
          value3: action trigger
